name: publish

on:
  release:
    types:
      - published

defaults: 
  run:
    shell: "bash"
    
jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v3
        
      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: "6.0.x"
          
      - name: "Echo current version number"
        run: echo "Current version is ${{ github.event.release.tag_name }}"

      - name: "Restore packages"
        run: dotnet restore
        
      - name: "Build"
        run: dotnet build -c Release --no-restore

      - name: "Test"
        run: dotnet test -c Release --no-build

      - name: "Pack"
        run: dotnet pack -c Release --no-build -o ./artifacts -p:PackageVersion=${{ github.event.release.tag_name }} ./MikanRss/MikanRss.csproj

      - name: "Publish"
        run: dotnet nuget push ./artifacts/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
